#!/bin/bash
# Maia OS - Quick Start Guide Script
# Muestra información rápida de inicio

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║                                              ║"
echo "║   ██████╗ ██╗   ██╗██╗     ██████╗ ██╗   ██╗ ║"
echo "║   ╚══███╔╝██║   ██║██║     ██╔══██╗╚██╗ ██╔╝ ║"
echo "║     ████╔╝ ██║   ██║██║     ██████╔╝ ╚████╔╝  ║"
echo "║    ██╔═══╝  ██║   ██║██║     ██╔══██╗  ╚██╔╝   ║"
echo "║   ███████╗╚██████╔╝███████╗██║  ██║   ██║    ║"
echo "║   ╚══════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝    ║"
echo "║                                              ║"
echo "║        Material 3 Expressive Edition         ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "¡Bienvenido a Maia OS!"
echo ""
echo "📦 Tu distribución Linux con Material 3 Expressive está lista"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 ARCHIVOS PRINCIPALES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📄 README.md"
echo "     → Documentación principal y características"
echo ""
echo "  🛠️  DEVELOPMENT.md"
echo "     → Guía completa de desarrollo y personalización"
echo ""
echo "  📜 LICENSE"
echo "     → Licencia GPL-3.0 y CC-BY-SA-4.0"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️  SCRIPTS DISPONIBLES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🔧 scripts/setup-build-env.sh"
echo "     → Instala todas las dependencias necesarias"
echo "     → Ejecutar PRIMERO: sudo ./scripts/setup-build-env.sh"
echo ""
echo "  🏗️  scripts/build-iso.sh"
echo "     → Construye la imagen ISO booteable"
echo "     → Requiere ~50GB de espacio libre"
echo "     → Ejecutar: sudo ./scripts/build-iso.sh"
echo ""
echo "  ✨ scripts/post-install.sh"
echo "     → Configuración post-instalación del sistema"
echo "     → Se ejecuta automáticamente en la ISO"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 INICIO RÁPIDO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Paso 1: Configurar entorno"
echo "    cd /workspace/maia-os"
echo "    sudo ./scripts/setup-build-env.sh"
echo ""
echo "  Paso 2: Construir ISO"
echo "    sudo ./scripts/build-iso.sh"
echo ""
echo "  Paso 3: Probar en máquina virtual"
echo "    qemu-system-x86_64 -m 4096 -cdrom output/maia-os-stable-x86_64.iso -boot d"
echo ""
echo "  Paso 4: Grabar en USB (opcional)"
echo "    sudo dd if=output/maia-os-stable-x86_64.iso of=/dev/sdX bs=4M status=progress"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎨 CARACTERÍSTICAS PRINCIPALES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ GNOME 45+ altamente personalizado"
echo "  ✓ Tema Material 3 Expressive completo"
echo "  ✓ Colores dinámicos estilo Material You"
echo "  ✓ Animaciones fluidas y naturales"
echo "  ✓ Bordes redondeados en toda la interfaz"
echo "  ✓ Fuentes Roboto Flex y Roboto Mono"
echo "  ✓ 18 aplicaciones preinstaladas"
echo "  ✓ Flatpak y Snap configurados"
echo "  ✓ Extensiones GNOME optimizadas"
echo "  ✓ Base Debian 12 estable"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 APLICACIONES PREINSTALADAS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • Maia Files       - Gestor de archivos M3E"
echo "  • Maia Browser     - Navegador web (Firefox)"
echo "  • Maia Terminal    - Terminal moderna"
echo "  • Maia Settings    - Configuración unificada"
echo "  • Maia Store       - Tienda de aplicaciones"
echo "  • Maia Media       - Reproductor multimedia"
echo "  • Maia Editor      - Editor de código"
echo "  • Maia Calculator  - Calculadora M3E"
echo "  • Maia Calendar    - Calendario y agenda"
echo "  • Maia Weather     - Aplicación del tiempo"
echo "  • Maia Photos      - Galería de fotos"
echo "  • Maia Music       - Reproductor de música"
echo "  • + Apps de productividad y desarrollo"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 ENLACES IMPORTANTES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🌐 Sitio web:     https://maia-os.org"
echo "  📥 Descargas:     https://releases.maia-os.org"
echo "  💬 Foro:          https://forum.maia-os.org"
echo "  🐛 Bugs:          https://github.com/maia-os/bugs"
echo "  📱 Telegram:      https://t.me/maiaos"
echo "  📖 Docs:          https://docs.maia-os.org"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 CONSEJOS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • Usa una máquina virtual para pruebas iniciales"
echo "  • Necesitas al menos 50GB libres para construir"
echo "  • La construcción puede tardar 30-60 minutos"
echo "  • Conecta a internet durante la construcción"
echo "  • Lee DEVELOPMENT.md para personalizar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ ¡Gracias por usar Maia OS!"
echo ""
echo "   \"Diseñado para humanos, construido para el futuro\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
